config/routes.rb
Rails.application.routes.draw do
  resources :pums
  resources :campaigns
  resources :pursuit_metrics
  resources :ces
  devise_for :users
   root to: "site#home"
end

app/models/pursuit_metric.rb
require 'net/sftp'
class PursuitMetric < ApplicationRecord
end

app/controllers/pursuit_metrics_controller.rb
class PursuitMetricsController < ApplicationController
  before_action :set_pursuit_metric, only: [:show, :edit, :update, :destroy]

  # GET /pursuit_metrics
  # GET /pursuit_metrics.json
  def index
    @pursuit_metrics = PursuitMetric.all
  end

  # GET /pursuit_metrics/1
  # GET /pursuit_metrics/1.json
  def show
  end

  # GET /pursuit_metrics/new
  def new
    @pursuit_metric = PursuitMetric.new
  end

  # GET /pursuit_metrics/1/edit
  def edit
  end

  # POST /pursuit_metrics
  # POST /pursuit_metrics.json
  def create
    @pursuit_metric = PursuitMetric.new(pursuit_metric_params)

    respond_to do |format|
      if @pursuit_metric.save
        format.html { redirect_to @pursuit_metric, notice: 'Pursuit metric was successfully created.' }
        format.json { render :show, status: :created, location: @pursuit_metric }
      else
        format.html { render :new }
        format.json { render json: @pursuit_metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pursuit_metrics/1
  # PATCH/PUT /pursuit_metrics/1.json
  def update
    respond_to do |format|
      if @pursuit_metric.update(pursuit_metric_params)
        format.html { redirect_to @pursuit_metric, notice: 'Pursuit metric was successfully updated.' }
        format.json { render :show, status: :ok, location: @pursuit_metric }
      else
        format.html { render :edit }
        format.json { render json: @pursuit_metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pursuit_metrics/1
  # DELETE /pursuit_metrics/1.json
  def destroy
    @pursuit_metric.destroy
    respond_to do |format|
      format.html { redirect_to pursuit_metrics_url, notice: 'Pursuit metric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pursuit_metric
      @pursuit_metric = PursuitMetric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pursuit_metric_params
      params.require(:pursuit_metric).permit(:date, :account_id, :custom, :earnings)
    end
end

app/helpers/pursuit_metrics_helper.rb
module PursuitMetricsHelper
end

app/views/pursuit_metrics/_form.html.erb
<%= simple_form_for(@pursuit_metric) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :account_id %>
    <%= f.input :custom %>
    <%= f.input :earnings %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pursuit_metrics/edit.html.erb
<h1>Editing Pursuit Metric</h1>

<%= render 'form', pursuit_metric: @pursuit_metric %>

<%= link_to 'Show', @pursuit_metric %> |
<%= link_to 'Back', pursuit_metrics_path %>

app/views/pursuit_metrics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pursuit Metrics</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Account</th>
      <th>Custom</th>
      <th>Earnings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pursuit_metrics.each do |pursuit_metric| %>
      <tr>
        <td><%= pursuit_metric.date %></td>
        <td><%= pursuit_metric.account_id %></td>
        <td><%= pursuit_metric.custom %></td>
        <td><%= pursuit_metric.earnings %></td>
        <td><%= link_to 'Show', pursuit_metric %></td>
        <td><%= link_to 'Edit', edit_pursuit_metric_path(pursuit_metric) %></td>
        <td><%= link_to 'Destroy', pursuit_metric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pursuit Metric', new_pursuit_metric_path %>

app/views/pursuit_metrics/new.html.erb
<h1>New Pursuit Metric</h1>

<%= render 'form', pursuit_metric: @pursuit_metric %>

<%= link_to 'Back', pursuit_metrics_path %>

app/views/pursuit_metrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @pursuit_metric.date %>
</p>

<p>
  <strong>Account:</strong>
  <%= @pursuit_metric.account_id %>
</p>

<p>
  <strong>Custom:</strong>
  <%= @pursuit_metric.custom %>
</p>

<p>
  <strong>Earnings:</strong>
  <%= @pursuit_metric.earnings %>
</p>

<%= link_to 'Edit', edit_pursuit_metric_path(@pursuit_metric) %> |
<%= link_to 'Back', pursuit_metrics_path %>