config/routes.rb
Rails.application.routes.draw do
  resources :pums
  resources :campaigns
  resources :pursuit_metrics
  resources :ces
  devise_for :users
   root to: "site#home"
end

app/models/pum.rb
require 'csv'
class Pum < ApplicationRecord
  before_validation :compute_id
  validates_uniqueness_of :computed_id

  def partner_records
    Ce.where(computed_id: computed_id)
  end

  def self.matches
   Pum.where("id < 340000").each do |p|
     ces = Ce.where(computed_id: p.computed_id)
     p p.id and break if ces.any?
    end
  end

  def self.process_google_drive
    download_export_files_from_google_drive
    save_csv_files_to_database
  end

  def self.save_local_files
    [ 'google', 'bing' ].each do |source|
      file_name = "db/files/#{source}-pursuit.csv"
      CSV.foreach(file_name, headers: true ).each_with_index do |row, i|
        Pum.save_csv_row(row: row)
      end
    end
  end

  def self.files
   {
    '1PSwvFyXFHaar9L6g7E4x0uDHc7YYGtPafar__Q37xvg'  =>  'bing.csv',
    '1xgshHf7QVqkMb8ko73W5SORaarwTP9kEvYEco7C3j6w'  =>  'google.csv'
   }
  end

  def self.download_export_files_from_google_drive
    google_drive = GoogleDrive.new
    files.each do |file_id, name|
      google_drive.download_file(file_id: file_id, name: name)
    end
  end

  def self.save_csv_files_to_database
    files.each do |file_id, name|
       CSV.foreach("#{name}", headers: true ).each do |row|
         Pum.save_csv_row(row: row)
      end
      File.unlink(name)
    end
  end

  def self.atts
    [
     "date", "account_name", "account_id", "campaign_name", "campaign_id", "ad_group_name", "ad_group_id",
     "device_type", "keyword", "keyword_id", "match_type", "keyword_status", "final_url", "final_mobile_url",
     "click_count", "conversions"
    ]
  end

 def self.save_csv_row(row:)
     pum = Pum.new
     pum.date                       = Chronic.parse(row[0])
     pum.account_name               = row[1]
     pum.account_id                 = row[2]
     pum.campaign_name              = row[3]
     pum.campaign_id                = row[4]
     pum.ad_group_name              = row[5]
     pum.ad_group_id                = row[6]
     pum.device_type = pum.campaign_name.match(/\(.*\)/)[0].gsub(/\W/, '')
     pum.keyword                    = row[8]
     pum.keyword_id                 = row[9]
     pum.match_type                 = row[10]
     pum.keyword_status             = row[11]
     pum.final_url                  = row[12]
     pum.final_mobile_url           = row[13]
     pum.click_count                = row[14].to_i
     pum.cost                       = row[15].to_f
     pum.conversions                = row[16].to_i

     pum.device_type                = "Desktop" if pum.device_type == "Tablets with Full Browsers" or  pum.device_type == "Computers"
     begin
       pum.save!
     rescue ActiveRecord::RecordInvalid
      p "updating dulicated record: #{pum.computed_id}"
      existing_pum = Pum.find_by(computed_id: pum.computed_id)
      existing_pum.cost += pum.cost
      existing_pum.click_count += pum.click_count
      existing_pum.conversions += pum.conversions
      existing_pum.save
     end
  end

  def self.send_report_to_google_drive(pums)
     timestamp = Time.zone.now.strftime("%Y-%m-%d-%H-%M")
     file_name = "#{timestamp}-export.csv"
     CSV.open(file_name, "wb") do |csv|
       csv << atts
       pums.each do |pum|
         csv << atts.map{ |attr| pum.send(attr) }
       end
     end
    google_drive = GoogleDrive.new
    google_drive.save_file_to_drive(file_name, file_name)
    File.unlink(file_name)
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << atts
        all.each do |pum|
        csv << atts.map{ |attr| pum.send(attr)  }
      end
    end
  end

 def self.import_csv_row(row)
   pum = Pum.new
   pum.date = Chronic.parse(row[0])
   pum.label = row[1]
   pum.account_id = row[2]
   pum.campaign_id = row[3]
   pum.ad_group_id = row[4]
   pum.keyword_id = row[5]
   pum.publisher  = row[6]
   pum.account_name = row[7]
   pum.campaign_name = row[8]
   pum.ad_group_name = row[9]
   pum.keyword = row[10]
   pum.focus_word = row[11]
   pum.industry = row[12]
   pum.device_type = pum.campaign.match(/\(.*\)/)[0].gsub(/\W/, '')
   pum.impressions = row[14].to_i
   pum.cost_per_click = row[15].to_f
   pum.cost = row[16].to_f
   pum.click_count = row[17].to_i
   pum.total_unreconciled_revenue = row[18].to_f
   pum.total_clickout_revenue = row[19].to_f
   pum.leads = row[20].to_i
   pum.clickouts = row[21].to_i
   pum.lead_users = row[22].to_i
   pum.lead_request_users = row[24].to_i
   pum.save
  end

  def compound_key
    keyword_id + ad_group_id + campaign_id + date.strftime("%Y-%m-%d")
  end

  def compute_id
    self.computed_id = Digest::MD5.hexdigest(compound_key)
  end

  private

end

app/controllers/pums_controller.rb
class PumsController < ApplicationController
  before_action :set_pum, only: [:show, :edit, :update, :destroy]
  #before_action :set_date_ranges

  def index
    # TODO ad date filters
    # scope = Pum.where(["date >= ? and date <= ?", @start_date, @end_date] )

    pum_ids = Pum.find_by_sql("select pums.id from pums, ces where ces.computed_id = pums.computed_id" ).collect(&:id)
    @start_date = (params[:start_date].present? ) ? Chronic.parse(params[:start_date] ) : Chronic.parse( Date.today - 1.week)
    @end_date = (params[:end_date].present? ) ? Chronic.parse(params[:end_date] ) : Chronic.parse( Date.today)
    @report = params[:report] || 'one'

    scope = Pum.where(id: pum_ids)
    scope = scope.where(label:         params[:label]         ) if params[:label].present?
    scope = scope.where(account_id:    params[:account_id]    ) if params[:account_id].present?
    scope = scope.where(campaign_id:   params[:campaign_id]   ) if params[:campaign_id].present?
    scope = scope.where(ad_group_id:   params[:ad_group_id]   ) if params[:ad_group_id].present?
    scope = scope.where(keyword_id:    params[:keyword_id]    ) if params[:keyword_id].present?
    scope = scope.where(publisher:     params[:publisher]     ) if params[:publisher].present?
    scope = scope.where(account_name:  params[:account_name]  ) if params[:account_name].present?
    scope = scope.where(campaign_name: params[:campaign_name] ) if params[:campaign_name].present?
    scope = scope.where(ad_group_name: params[:ad_group_name] ) if params[:ad_group_name].present?
    scope = scope.where(keyword:       params[:key_word]      ) if params[:key_word].present?
    scope = scope.where(focus_word:    params[:focus_word]    ) if params[:focus_word].present?
    scope = scope.where(industry:      params[:industry]      ) if params[:industry].present?
    scope = scope.where(device_type:   params[:device_type]   ) if params[:device_type].present?

    @sort_order = params[:sort_order] || 'asc'
    @next_sort_order = ( @sort_order == 'desc' ) ? 'asc' : 'desc'
    @sort_property = params[:sort_property] || 'date'

    if params[:format] == "csv"
      @pums = scope.order( { @sort_property => @sort_order } )
    else
      @pums = scope.page(params[:page]).order( { @sort_property => @sort_order } ).per(1220)
    end
    if params[:export].present?
      Pum.send_report_to_google_drive(@pums)
    end
    respond_to do |format|
      format.html
      format.csv do
        send_data @pums.to_csv, filename: "pursuit-media-#{Date.today.strftime("%m-%d-%Y")}.csv"
      end
    end
  end

  private

  def set_date_ranges
    @start_date = (params[:report].present?) ? Chronic.parse("#{params[:report]["start_date(1i)"]}-#{params[:report]["start_date(2i)"]}-#{params[:report]["start_date(3i)"]}").utc.beginning_of_day : Date.today - 7.days
    @end_date = (params[:report].present?) ? Chronic.parse("#{params[:report]["end_date(1i)"]}-#{params[:report]["end_date(2i)"]}-#{params[:report]["end_date(3i)"]}").utc.end_of_day : Date.today
    @start_date = Chronic.parse(params[:start_date]).utc.beginning_of_day  - 3.days if params[:start_date].present?
    @end_date = Chronic.parse(params[:end_date]).utc.at_end_of_day + 1.day if params[:end_date].present?
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_pum
      @pum = Pum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pum_params
      params.require(:pum).permit(:date, :label, :account_id, :campaign_id, :ad_group_id, :keyword_id, :publisher, :account_name, :campaign_name, :ad_group_name, :keyword, :focus_word, :industry, :device_type, :impressions, :cost_per_click, :cost, :click_count, :total_unreconciled_revenue, :total_clickout_revenue, :leads, :clickouts, :lead_users, :lead_request_users)
    end
end

app/helpers/pums_helper.rb
module PumsHelper
end

app/views/pums/_form.html.erb
<%= simple_form_for(@pum) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :label %>
    <%= f.input :account_id %>
    <%= f.input :campaign_id %>
    <%= f.input :ad_group_id %>
    <%= f.input :keyword_id %>
    <%= f.input :publisher %>
    <%= f.input :account_name %>
    <%= f.input :campaign_name %>
    <%= f.input :ad_group_name %>
    <%= f.input :keyword %>
    <%= f.input :focus_word %>
    <%= f.input :industry %>
    <%= f.input :device_type %>
    <%= f.input :impressions %>
    <%= f.input :cost_per_click %>
    <%= f.input :cost %>
    <%= f.input :click_count %>
    <%= f.input :total_unreconciled_revenue %>
    <%= f.input :total_clickout_revenue %>
    <%= f.input :leads %>
    <%= f.input :clickouts %>
    <%= f.input :lead_users %>
    <%= f.input :lead_request_users %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pums/_search_criteria.html.erb
<% if @report == "one" %>
<h4>Pursuit Media Group Keyword Merged Data</h4>
Exported  Weekly
<% elsif @report == "two" %>
<h4>Pursuit Media Group Campaign Merged Data  (2)</h4>
Notes
Remove Kewword ID
Keyword
Ad Group ID
Ad Group Name
Sum Everything under campign id
Exported Daily
<% elsif @report == "three" %>
<h4>Pursuit Media Group Merged Data (3)</h4>
Exported  Weekly
<% elsif @report == "four" %>
<h4>Pursuit Media Group Merged Data (4)</h4>
 Exported Daily
<% end %>

<%= form_tag pums_path, role: 'search',  method: :get do |f| %>

<div class="row">

<div class="col m1">
   <%= text_field_tag :start_date, @start_date.strftime("%m/%d/%Y"), class: "datepicker", placeholder: "Start Date" -%>
</div>

<div class="col m1">
   <%= text_field_tag :label, params[:label], type: 'search', placeholder: 'Label' -%>
</div>

<div class="col m1">
   <%= text_field_tag :account_id, params[:account_id], type: 'search', placeholder: 'Account Id' -%>
</div>

<div class="col m1">
   <%= text_field_tag :campaign_id, params[:campaign_id], type: 'search', placeholder: 'Campaign Id' -%>
</div>

<div class="col m1">
   <%= text_field_tag :ad_group_id, params[:ad_group_id], type: 'search', placeholder: 'Ad Group Id' -%>
</div>

<div class="col m1">
   <%= text_field_tag :keyword_id, params[:keyword_id], type: 'search', placeholder: 'Keyword ID' -%>
</div>

<div class="col m1">
   <%= text_field_tag :publisher, params[:publisher], type: 'search', placeholder: 'Publisher' -%>
</div>
</div>

<div class="row">

<div class="col m1">
   <%= text_field_tag :end_date, @end_date.strftime("%m/%d/%Y"), class: "datepicker", placeholder: "End Date" -%>
</div>

<div class="col m1">
   <%= text_field_tag :account_name, params[:account_name], type: 'search', placeholder: 'Account Name' -%>
</div>

<div class="col m1">
   <%= text_field_tag :campaign_name, params[:campaign_name], type: 'search', placeholder: 'Campaign Name' -%>
</div>

<div class="col m1">
   <%= text_field_tag :ad_group_name, params[:ad_group_name], type: 'search', placeholder: 'Ad Group Name' -%>
</div>

<div class="col m1">
   <%= text_field_tag :key_word, params[:key_word], type: 'search', placeholder: 'Keyword' -%>
</div>

<div class="col m1">
   <%= text_field_tag :focus_word, params[:focus_word], type: 'search', placeholder: 'Focus Word' -%>
</div>

<div class="col m1">
   <%= text_field_tag :industry, params[:industry], type: 'search', placeholder: 'Industry' -%>
</div>

<div class="col m1">
   <%= text_field_tag :device_type, params[:device_type], type: 'search', placeholder: 'Device Type' -%>
</div>

</div>

<div class="row">
<% if false %>
  <div class="col m4">
     <%= link_to "Report One", request.params.merge(report: "one") , class: "btn margined #{@report == 'one' ? 'blue' : '' }" -%>
     <%= link_to "Report Two", request.params.merge(report: "two") , class: "btn margined #{@report == 'two' ? 'blue' : '' }" -%>
     <%= link_to "Report Three", request.params.merge(report: "three") , class: "btn margined #{@report == 'three' ? 'blue' : '' }" -%>
     <%= link_to "Report Four", request.params.merge(report: "four")  , class: "btn margined #{@report == 'four' ? 'blue' : '' }" -%>
  </div>
<% end %>


<div class="col m5">
   <%= submit_tag 'Search', class: 'btn margined' %>
   <%= link_to 'Export to CSV', request.params.merge(format: :csv), class: 'btn margined' -%>
   <%= link_to 'Save to Google', request.params.merge(export: :google), class: 'btn margined' -%>
   <%= link_to 'Clear', pums_path, class: 'btn margined' -%>
</div>

</div>
<% end %>

app/views/pums/_search_results_one.html.erb
<div class="row">
<div class="col m12">

<small>
<table class="highlight">
  <thead>
    <tr>
      <th><%= link_to 'Computed Id', request.params.merge(sort_property: 'computed_id', sort_order: @next_sort_order)-%> </th>
      <th>Matches</th>
      <th>Date</th>
      <th><%= link_to 'Label', request.params.merge(sort_property: 'label', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Account ID', request.params.merge(sort_property: 'account_id', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Campaign Id', request.params.merge(sort_property: 'campaign_id', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Ad Group Id', request.params.merge(sort_property: 'ad_group_id', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Keyword Id', request.params.merge(sort_property: 'keyword_id', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Match Type ', request.params.merge(sort_property: 'match_type', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Publisher', request.params.merge(sort_property: 'publisher', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Account Name', request.params.merge(sort_property: 'account_name', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Campaign Name', request.params.merge(sort_property: 'campaign_name', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Ad Group Name', request.params.merge(sort_property: 'ad_group_name', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Keyword', request.params.merge(sort_property: 'keyword', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Keyword Status', request.params.merge(sort_property: 'keyword_status', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Focus Word', request.params.merge(sort_property: 'focus_word', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Industry', request.params.merge(sort_property: 'industry', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Device Type', request.params.merge(sort_property: 'device_type', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Impressions', request.params.merge(sort_property: 'impressions', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'CPC', request.params.merge(sort_property: 'cost_per_click', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Cost', request.params.merge(sort_property: 'cost', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Click Count', request.params.merge(sort_property: 'click_count', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Total Unreconciled Revenue', request.params.merge(sort_property: 'total_unreconciled_revenue', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Total Clickout Revenue', request.params.merge(sort_property: 'total_clickout_revenue', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Leads', request.params.merge(sort_property: 'leads', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Clickouts', request.params.merge(sort_property: 'clickouts', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Lead Users', request.params.merge(sort_property: 'lead_users', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Lead Request Users', request.params.merge(sort_property: 'lead_request_users', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Conversions', request.params.merge(sort_property: 'conversions', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Final Url', request.params.merge(sort_property: 'final_url', sort_order: @next_sort_order)-%> </th>
      <th><%= link_to 'Final Mobile Url', request.params.merge(sort_property: 'final_mobile_url', sort_order: @next_sort_order)-%> </th>
    </tr>
  </thead>

  <tbody>
    <% @pums.each do |pum| %>
      <tr>
        <td><%= pum.computed_id -%></td>
        <td>
           <% Ce.where(computed_id: pum.computed_id).each do |ce| -%>
             <%= link_to 'view', ce_path(ce) -%>
           <% end %>
        </td>
        <td><%= pum.date.strftime("%m-%d-%Y") %></td>
        <td><%= pum.label %></td>
        <td><%= pum.account_id %></td>
        <td><%= pum.campaign_id %></td>
        <td><%= pum.ad_group_id %></td>
        <td><%= pum.keyword_id %></td>
        <td><%= pum.match_type %></td>
        <td><%= pum.publisher %></td>
        <td><%= pum.account_name %></td>
        <td><%= pum.campaign_name %></td>
        <td><%= pum.ad_group_name %></td>
        <td><%= pum.keyword %></td>
        <td><%= pum.keyword_status %></td>
        <td><%= pum.focus_word %></td>
        <td><%= pum.industry %></td>
        <td><%= pum.device_type %></td>
        <td><%= pum.impressions %></td>
        <td><%= pum.cost_per_click %></td>
        <td><%= pum.cost %></td>
        <td><%= pum.click_count %></td>
        <td><%= pum.total_unreconciled_revenue %></td>
        <td><%= pum.total_clickout_revenue %></td>
        <td><%= pum.leads %></td>
        <td><%= pum.clickouts %></td>
        <td><%= pum.lead_users %></td>
        <td><%= pum.lead_request_users %></td>
        <td><%= pum.conversions -%></td>
        <td><%= pum.final_url -%></td>
        <td><%= pum.final_mobile_url -%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate(@pums)-%>

</small>

</div>
</div>

app/views/pums/edit.html.erb
<h1>Editing Pum</h1>

<%= render 'form', pum: @pum %>

<%= link_to 'Show', @pum %> |
<%= link_to 'Back', pums_path %>

app/views/pums/index.html.erb
<%= render partial: "search_criteria" -%>
<% if @report == 'one'%>
<%= render partial: "search_results_one" -%>
<% elsif @report == 'two'%>
<%= render partial: "search_results_two" -%>
<% elsif @report == 'three'%>
<%= render partial: "search_results_three" -%>
<% elsif @report == 'four' %>
<%= render partial: "search_results_four" -%>
<% end %>

app/views/pums/new.html.erb
<h1>New Pum</h1>

<%= render 'form', pum: @pum %>

<%= link_to 'Back', pums_path %>

app/views/pums/show.html.erb
<table class="striped">

<tr>
<td>

<p>
  <% @ce = Ce.find_by(computed_id: @pum.computed_id) %>
  <%= link_to 'Revenue record', ce_path(@ce) -%>
</p>

<p>
  <strong>Date:</strong>
  <%= @pum.date %>
</p>

<p>
  <strong>Label:</strong>
  <%= @pum.label %>
</p>

<p>
  <strong>Account:</strong>
  <%= @pum.account_id %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @pum.campaign_id %>
</p>

<p>
  <strong>Ad group:</strong>
  <%= @pum.ad_group_id %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @pum.keyword_id %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @pum.publisher %>
</p>

<p>
  <strong>Account name:</strong>
  <%= @pum.account_name %>
</p>

<p>
  <strong>Campaign name:</strong>
  <%= @pum.campaign_name %>
</p>

<p>
  <strong>Ad group name:</strong>
  <%= @pum.ad_group_name %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @pum.keyword %>
</p>

<p>
  <strong>Focus word:</strong>
  <%= @pum.focus_word %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @pum.industry %>
</p>

<p>
  <strong>Device type:</strong>
  <%= @pum.device_type %>
</p>

<p>
  <strong>Impressions:</strong>
  <%= @pum.impressions %>
</p>

<p>
  <strong>Cost per click:</strong>
  <%= @pum.cost_per_click %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @pum.cost %>
</p>

<p>
  <strong>Click count:</strong>
  <%= @pum.click_count %>
</p>

<p>
  <strong>Total unreconciled revenue:</strong>
  <%= @pum.total_unreconciled_revenue %>
</p>

<p>
  <strong>Total clickout revenue:</strong>
  <%= @pum.total_clickout_revenue %>
</p>

<p>
  <strong>Leads:</strong>
  <%= @pum.leads %>
</p>

<p>
  <strong>Clickouts:</strong>
  <%= @pum.clickouts %>
</p>

<p>
  <strong>Lead users:</strong>
  <%= @pum.lead_users %>
</p>

<p>
  <strong>Lead request users:</strong>
  <%= @pum.lead_request_users %>
</p>

</td>
</tr>

</table>