config/routes.rb
Rails.application.routes.draw do
  resources :pums
  resources :campaigns
  resources :pursuit_metrics
  resources :ces
  devise_for :users
   root to: "site#home"
end

app/models/ce.rb
require 'csv'
require 'tempfile'

class Ce < ApplicationRecord
 SFTP_HOST = 'campusexplorer.brickftp.com'
 SFTP_USERNAME = 'criminaljusticepursuit'
 SFTP_PASSWORD = 'UlRh1Lz&iuq4'

  after_validation :parse_source_code_field
  after_validation :compute_id

  def self.save_last_entry_data
    read_last_entry_data.each {|row| save_row(row)}
  end

  def self.save_row(r)
    row = r.split(',')
    ce = Ce.new
    ce.grouping_date = Chronic.parse(row[0])
    ce.lead_request_users = row[1].to_i
    ce.lead_users = row[2].to_i
    ce.leads = row[3].to_i
    ce.leads_by_lead_users = row[4].to_f
    ce.unreconciled_publisher_lead_revenue = row[5].to_f
    ce.clickout_impressions = row[6].to_i
    ce.clickouts = row[7].to_i
    ce.clickthrough_rate = row[8].to_f
    ce.unreconciled_publisher_clickout_revenue = row[9].to_f
    ce.unreconciled_publisher_total_revenue = row[10].to_f
    ce.source_code = row[11]
    ce.tracking_code = row[12]
    ce.adult_lead_request_users = row[13].to_i
    ce.adult_lead_users = row[14].to_i
    ce.adult_leads = row[15].to_i
    ce.adult_leads_by_lead_users = row[16].to_f
    ce.adult_unreconciled_publisher_lead_revenue = row[17].to_f
    ce.adult_clickouts = row[18].to_i
    ce.adult_clickout_revenue = row[19].to_i
    ce.hs_lead_request_users = row[20].to_i
    ce.hs_lead_users = row[21].to_f
    ce.hs_leads = row[22].to_i
    ce.hs_leads_by_lead_users = row[23].to_f
    ce.hs_unreconciled_published_clickout_revenue = row[24].to_f
    ce.hs_clickouts = row[25].to_i
    ce.hs_clickout_revenue = row[26].to_f
    ce.save
  end

  def self.save_csv_to_google_drive
    to_csv
    google_drive = GoogleDrive.new
    google_drive.save_file_to_drive(file_name, file_name)
  end

  def self.file_name
    "campus-explorer-#{Date.today.strftime("%Y-%m-%d")}.csv"
  end

  def self.to_csv
    CSV.open(file_name, 'wb') do |csv|
      Ce.all.each do |ce|
        row = []
        Ce.cols.each { |col| row << ce.send(col) }
        csv << row
      end
    end
  end

  def self.read_last_entry_data
    lines = []
    last_entry_data.split(/\n/).each_with_index do |line,i|
      next if i == 0
       lines << line
    end
    lines
  end

  def self.save_last_entry_to_google_drive
    file = File.open(file_name, 'w')
    file.write last_entry_data
    file.close
    google_drive = GoogleDrive.new
    google_drive.save_file_to_drive(file_name, file_name)
  end

  def self.last_entry_data
    sftp.download(remote_path: '/' + last_entry )
  end

  def self.last_entry
    sftp.read_remote_directory(directory_path: '/').last
  end

  def self.sftp
    FalconSftp.new(SFTP_HOST,SFTP_USERNAME,SFTP_PASSWORD)
  end

  def parse_source_code_field
    a = self.source_code.split('_')
    return if a.size < 3
    self.campaign_id = a[2].gsub('cp-', '')
    self.adgroup_id = a[3].gsub('ag-', '')
    self.keyword_id = a[5].gsub(/\D/, '') if a[5].present?
    self.page_variation_1 = a[6].gsub('p1var-', '') if a[6].present?
    self.page_variation_2 = a[7].gsub('p2var-', '') if a[7].present?
    self.publisher = ( a[1] == 'pb-b1') ? 'bing' : 'google'
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << cols
        all.each do |ce|
        csv << cols.map{ |attr| ce.send(attr)  }
      end
    end
  end

  def self.cols
   [:computed_id, :publisher, :grouping_date, :campaign_id , :adgroup_id, :keyword_id, :page_variation_1,
    :page_variation_2, :lead_request_users, :lead_users, :leads, :leads_by_lead_users,
    :unreconciled_publisher_lead_revenue, :clickout_impressions, :clickouts, :clickthrough_rate,
    :unreconciled_publisher_clickout_revenue, :unreconciled_publisher_total_revenue, :source_code, :tracking_code,
    :adult_lead_request_users, :adult_lead_users, :adult_leads, :adult_leads_by_lead_users,
    :adult_unreconciled_publisher_lead_revenue, :adult_clickouts, :adult_clickout_revenue, :hs_lead_request_users,
    :hs_lead_users, :hs_leads, :hs_leads_by_lead_users, :hs_unreconciled_published_clickout_revenue, :hs_clickouts, :hs_clickout_revenue
   ]
  end

  def compound_key
    return '' if keyword_id.blank?
    keyword_id + adgroup_id + campaign_id + grouping_date.strftime("%Y-%m-%d")
  end

  def compute_id
    self.computed_id = Digest::MD5.hexdigest(compound_key)
  end

end

app/controllers/ces_controller.rb
class CesController < ApplicationController
  before_action :set_ce, only: [:show, :edit, :update, :destroy]

  # GET /ces
  # GET /ces.json
  def index
    scope = Ce
    scope = scope.where(publisher: params[:publisher]) if params[:publisher].present?
    scope = scope.where(campaign_id: params[:campaign_id]) if params[:campaign_id].present?
    scope = scope.where(adgroup_id: params[:adgroup_id]) if params[:adgroup_id].present?
    respond_to  do |format|
      format.html do
        @ces = scope.order(grouping_date: :asc).page(params[:page]).per(100)
      end
      format.csv do
        @ces = scope
        send_data @ces.to_csv, filename: "campus-explorer-#{Date.today.strftime("%m-%d-%Y")}.csv"
      end
    end
  end

  # GET /ces/1
  # GET /ces/1.json
  def show
  end

  # GET /ces/new
  def new
    @ce = Ce.new
  end

  # GET /ces/1/edit
  def edit
  end

  # POST /ces
  # POST /ces.json
  def create
    @ce = Ce.new(ce_params)

    respond_to do |format|
      if @ce.save
        format.html { redirect_to @ce, notice: 'Ce was successfully created.' }
        format.json { render :show, status: :created, location: @ce }
      else
        format.html { render :new }
        format.json { render json: @ce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ces/1
  # PATCH/PUT /ces/1.json
  def update
    respond_to do |format|
      if @ce.update(ce_params)
        format.html { redirect_to @ce, notice: 'Ce was successfully updated.' }
        format.json { render :show, status: :ok, location: @ce }
      else
        format.html { render :edit }
        format.json { render json: @ce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ces/1
  # DELETE /ces/1.json
  def destroy
    @ce.destroy
    respond_to do |format|
      format.html { redirect_to ces_url, notice: 'Ce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ce
      @ce = Ce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ce_params
      params.fetch(:ce, {})
    end
end

app/helpers/ces_helper.rb
module CesHelper
end

app/views/ces/_form.html.erb
<%= simple_form_for(@ce) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ces/edit.html.erb
<h1>Editing Ce</h1>

<%= render 'form', ce: @ce %>

<%= link_to 'Show', @ce %> |
<%= link_to 'Back', ces_path %>

app/views/ces/index.html.erb
<h1>Revenue</h1>
<%= link_to ces_path(format: :csv), class: 'left' do %>
  Export
  <i class="material-icons">grid_on</i>
<% end %>

<%= form_tag ces_path, role: 'search',  method: :get do |f| %>
  <div class="row">
    <div class="col m1">
     <%= text_field_tag :publisher, params[:publisher], type: 'search', placeholder: 'Publisher' -%>
    </div>

    <div class="col m1">
     <%= text_field_tag :campaign_id, params[:campaign_id], type: 'search', placeholder: 'Campaign ID' -%>
    </div>

    <div class="col m2">
     <%= text_field_tag :adgroup_id, params[:adgroup_id], type: 'search', placeholder: 'Ad Group ID' -%>
    </div>

    <div class="col m1">
      <%= submit_tag  "search" %>
    </div>
</div>

<% end %>

<div class="row">
<div class="col m12 s12">

<table class="striped">
  <thead>
     <th>Matches</th>
      <% Ce.cols.each do |col| %>
       <th><%= col -%> </th>
      <% end %>
  </thead>

  <tbody>
    <% @ces.each do |ce| %>
      <tr>
        <td>
         <%= Pum.where(computed_id: ce.computed_id).count  %>
         </td>
         <% Ce.cols.each do |col| %>
           <td>
             <% if col == :grouping_date %>
             <%= ce.send(col).strftime("%m-%d-%Y") -%>
             <% else %>
             <%= ce.send(col) -%>
             <% end %>
           </td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate(@ces) -%>

</div>
</div>

app/views/ces/new.html.erb
<h1>New Ce</h1>

<%= render 'form', ce: @ce %>

<%= link_to 'Back', ces_path %>

app/views/ces/show.html.erb
<h1>Partner Revenue Detail (Campus Explorer)</h1>

<table class="striped">
  <tr>
    <td>
      <% Ce.cols.each do |col| %>
        <p> <%= col.to_s -%> :
        <% if col == :grouping_date %>
          <%= @ce.send(col).strftime("%m-%d-%Y") -%>
        <% else %>
          <%= @ce.send(col) -%>
        <% end %>
      <% end %>
       </p>
     </td>
    <td style="vertical-align: baseline;">
      <% @pum = Pum.find_by(computed_id: @ce.computed_id)  %>
      <% if @pum.present? %>
        <%= link_to 'Spending Record', pum_path(@pum) -%>
        <% Pum.atts.each do |col| %>
         <p> <%= col.to_s -%> :
          <% if col == :grouping_date %>
            <%= @pum.send(col).strftime("%m-%d-%Y") -%>
          <% else %>
            <%= @pum.send(col) -%>
          <% end %>
        <% end %>
       </p>
     <% end %>
   </td>
 </tr>
</table>